version: "3.8"
services:
  client:
    build: ./Core/src/client
    depends_on:
      - redis
      - server
    ports:
      - "3000:3000"
  server:
    build: ./Core/src/server
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  redis:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./Core/src/data/redis:/bitnami/redis/data
    ports:
      - "6379:6379"
  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./Core/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "80:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=marihuana
    
  
